namespace CastoPet.Tests;

internal static partial class TestSuite
{
    internal static IReadOnlyList<(string Name, Action Test)> Tests { get; } = new (string Name, Action Test)[]
    {
        ("Default settings match MVP defaults", DefaultSettingsMatchMvpDefaults),
        ("Default active movement is disabled", DefaultActiveMovementIsDisabled),
        ("Default push cursor is disabled", DefaultPushCursorIsDisabled),
        ("Default input reactive mode is disabled", DefaultInputReactiveModeIsDisabled),
        ("Default theme follows the system", DefaultThemeFollowsTheSystem),
        ("Settings round trip as JSON", SettingsRoundTripAsJson),
        ("Settings round trip includes active movement", SettingsRoundTripIncludesActiveMovement),
        ("Settings round trip includes push cursor", SettingsRoundTripIncludesPushCursor),
        ("Settings round trip includes input reactive mode", SettingsRoundTripIncludesInputReactiveMode),
        ("Settings round trip includes skin manifest path", SettingsRoundTripIncludesSkinManifestPath),
        ("Settings round trip includes theme mode", SettingsRoundTripIncludesThemeMode),
        ("Settings save is atomic and versioned", SettingsSaveIsAtomicAndVersioned),
        ("Settings load restores the last valid backup", SettingsLoadRestoresTheLastValidBackup),
        ("Settings load migrates legacy schema", SettingsLoadMigratesLegacySchema),
        ("Settings transaction rolls back failed persistence", SettingsTransactionRollsBackFailedPersistence),
        ("App paths include local crash reports", AppPathsIncludeLocalCrashReports),
        ("Product identities isolate stable and preview", ProductIdentitiesIsolateStableAndPreview),
        ("App paths follow product identity", AppPathsFollowProductIdentity),
        ("Preview data migration copies user configuration once", PreviewDataMigrationCopiesUserConfigurationOnce),
        ("Settings round trip includes crash and update state", SettingsRoundTripIncludesCrashAndUpdateState),
        ("Settings clone includes crash and update state", SettingsCloneIncludesCrashAndUpdateState),
        ("Settings clone includes theme mode", SettingsCloneIncludesThemeMode),
        ("Theme mode resolves system preference", ThemeModeResolvesSystemPreference),
        ("Settings theme palette defines light and dark contrast", SettingsThemePaletteDefinesLightAndDarkContrast),
        ("Settings theme palette replaces frozen brushes", SettingsThemePaletteReplacesFrozenBrushes),
        ("Windows system theme reader handles app preference", WindowsSystemThemeReaderHandlesAppPreference),
        ("Settings backdrop targets supported Windows versions", SettingsBackdropTargetsSupportedWindowsVersions),
        ("Crash reports sanitize user paths and include exception chains", CrashReportsSanitizeUserPathsAndIncludeExceptionChains),
        ("Crash reports include edition and source commit", CrashReportsIncludeEditionAndSourceCommit),
        ("Build information parses SDK source revisions", BuildInformationParsesSdkSourceRevisions),
        ("Crash reports keep a bounded log tail", CrashReportsKeepABoundedLogTail),
        ("Crash report service writes and acknowledges reports", CrashReportServiceWritesAndAcknowledgesReports),
        ("Diagnostic reports do not trigger crash notifications", DiagnosticReportsDoNotTriggerCrashNotifications),
        ("Crash report service contains file system failures", CrashReportServiceContainsFileSystemFailures),
        ("Crash report service prunes old reports", CrashReportServicePrunesOldReports),
        ("Crash report retention orders fatal and diagnostic reports together", CrashReportRetentionOrdersFatalAndDiagnosticReportsTogether),
        ("Unobserved tasks do not consume the fatal crash quota", UnobservedTasksDoNotConsumeTheFatalCrashQuota),
        ("Application registers all unhandled exception sources", ApplicationRegistersAllUnhandledExceptionSources),
        ("Application cancels automatic update work on exit", ApplicationCancelsAutomaticUpdateWorkOnExit),
        ("Crash notification is local only", CrashNotificationIsLocalOnly),
        ("Update policy checks at most once per local day", UpdatePolicyChecksAtMostOncePerLocalDay),
        ("Manual update checks bypass the daily gate", ManualUpdateChecksBypassTheDailyGate),
        ("Update coordinator skips development builds", UpdateCoordinatorSkipsDevelopmentBuilds),
        ("Preview update service stays disabled", PreviewUpdateServiceStaysDisabled),
        ("Update coordinator records automatic attempts before network", UpdateCoordinatorRecordsAutomaticAttemptsBeforeNetwork),
        ("Update coordinator maps network failures", UpdateCoordinatorMapsNetworkFailures),
        ("Update coordinator logs network failures", UpdateCoordinatorLogsNetworkFailures),
        ("Update coordinator rejects concurrent checks", UpdateCoordinatorRejectsConcurrentChecks),
        ("Project pins semantic version and Velopack", ProjectPinsSemanticVersionAndVelopack),
        ("Application defines packaged icon", ApplicationDefinesPackagedIcon),
        ("Application surfaces share one icon", ApplicationSurfacesShareOneIcon),
        ("Tray service disposes owned menu resources", TrayServiceDisposesOwnedMenuResources),
        ("Settings window avoids a duplicate taskbar entry", SettingsWindowAvoidsDuplicateTaskbarEntry),
        ("Continuous integration builds both configurations", ContinuousIntegrationBuildsBothConfigurations),
        ("Project supports stable and preview resource profiles", ProjectSupportsStableAndPreviewResourceProfiles),
        ("Packaging script builds traceable edition-specific installers", PackagingScriptBuildsTraceableEditionSpecificInstallers),
        ("Packaging workflow produces manual artifacts without publishing", PackagingWorkflowProducesManualArtifactsWithoutPublishing),
        ("Repository ignores local working assets", RepositoryIgnoresLocalWorkingAssets),
        ("Velopack runs at the application entry point", VelopackRunsAtTheApplicationEntryPoint),
        ("Update source points to the public releases repository", UpdateSourcePointsToThePublicReleasesRepository),
        ("Settings window exposes crash and update actions", SettingsWindowExposesCrashAndUpdateActions),
        ("Pet window settings snapshot copies runtime flags", PetWindowSettingsSnapshotCopiesRuntimeFlags),
        ("Pet window settings snapshot copies input reactive mode", PetWindowSettingsSnapshotCopiesInputReactiveMode),
        ("Invalid settings file falls back to defaults", InvalidSettingsFallsBackToDefaults),
        ("Logging writes a dated log file", LoggingWritesDatedLogFile),
        ("Logging rotates bounded archive files", LoggingRotatesBoundedArchiveFiles),
        ("Bottom-right placement uses work area margin", BottomRightPlacementUsesWorkAreaMargin),
        ("Startup value name is CastoPet", StartupValueNameIsCastoPet),
        ("Startup service accepts product registration identity", StartupServiceAcceptsProductRegistrationIdentity),
        ("Startup registration matches current executable path", StartupRegistrationMatchesCurrentExecutablePath),
        ("Project does not keep template MainWindow", ProjectDoesNotKeepTemplateMainWindow),
        ("Single instance rejects a second owner", SingleInstanceRejectsSecondOwner),
        ("Application composes the current product identity", ApplicationComposesTheCurrentProductIdentity),
        ("Single instance restore signal reaches primary", SingleInstanceRestoreSignalReachesPrimary),
        ("Runtime position starts at default", RuntimePositionStartsAtDefault),
        ("Runtime position tracks drag for current run only", RuntimePositionTracksDragForCurrentRunOnly),
        ("Show restore keeps hidden position but resets visible position", ShowRestoreKeepsHiddenPositionButResetsVisiblePosition),
        ("Built-in Castorice skin defines required actions", BuiltInCastoriceSkinDefinesRequiredActions),
        ("Built-in Castorice skin uses runtime asset root", BuiltInCastoriceSkinUsesRuntimeAssetRoot),
        ("Built-in Castorice idle action preserves current frames", BuiltInCastoriceIdleActionPreservesCurrentFrames),
        ("Built-in Castorice move action preserves movement values", BuiltInCastoriceMoveActionPreservesMovementValues),
        ("Built-in Castorice defines separate directional movement actions", BuiltInCastoriceDefinesSeparateDirectionalMovementActions),
        ("Built-in directional frames are embedded WPF resources", BuiltInDirectionalFramesAreEmbeddedWpfResources),
        ("Built-in Castorice blink action preserves schedule", BuiltInCastoriceBlinkActionPreservesSchedule),
        ("Built-in Castorice defines optional petting action", BuiltInCastoriceDefinesOptionalPettingAction),
        ("Built-in petting frames are packaged and clean", BuiltInPettingFramesArePackagedAndClean),
        ("Built-in Castorice expressions are ordered skin definitions", BuiltInCastoriceExpressionsAreOrderedSkinDefinitions),
        ("Built-in Castorice loads from embedded manifest", BuiltInCastoriceLoadsFromEmbeddedManifest),
        ("Pet skin manifest loads JSON resource paths", PetSkinManifestLoadsJsonResourcePaths),
        ("Pet skin manifest loads per-frame action durations", PetSkinManifestLoadsPerFrameActionDurations),
        ("Pet skin manifest loads expression transition metadata", PetSkinManifestLoadsExpressionTransitionMetadata),
        ("Pet skin manifest loads file paths relative to manifest", PetSkinManifestLoadsFilePathsRelativeToManifest),
        ("External skin rejects paths outside its resource root", ExternalSkinRejectsPathsOutsideItsResourceRoot),
        ("External skin rejects reparse point escapes", ExternalSkinRejectsReparsePointEscapes),
        ("External skin enforces manifest and frame budgets", ExternalSkinEnforcesManifestAndFrameBudgets),
        ("External skin validates PNG files and dimensions", ExternalSkinValidatesPngFilesAndDimensions),
        ("Pet skin manifest requires core actions", PetSkinManifestRequiresCoreActions),
        ("Pet skin manifest rejects duplicate actions", PetSkinManifestRejectsDuplicateActions),
        ("Pet skin manifest rejects invalid action metadata", PetSkinManifestRejectsInvalidActionMetadata),
        ("Pet skin manifest rejects invalid per-frame durations", PetSkinManifestRejectsInvalidPerFrameDurations),
        ("Pet skin manifest writer emits loadable JSON", PetSkinManifestWriterEmitsLoadableJson),
        ("Pet skin manifest writer round trips per-frame durations", PetSkinManifestWriterRoundTripsPerFrameDurations),
        ("Pet skin manifest writer stores paths relative to resource root", PetSkinManifestWriterStoresPathsRelativeToResourceRoot),
        ("Pet skin manifest round trips optional petting action", PetSkinManifestRoundTripsOptionalPettingAction),
        ("Pet skin selection defaults to built-in skin", PetSkinSelectionDefaultsToBuiltInSkin),
        ("Pet skin selection loads configured manifest", PetSkinSelectionLoadsConfiguredManifest),
        ("Pet skin selection falls back when manifest fails", PetSkinSelectionFallsBackWhenManifestFails),
        ("Asset service defaults to built-in skin", AssetServiceDefaultsToBuiltInSkin),
        ("Asset service uses configured skin paths", AssetServiceUsesConfiguredSkinPaths),
        ("Asset service loads file system skin image paths", AssetServiceLoadsFileSystemSkinImagePaths),
        ("Asset service loads expression images with isolated transitions", AssetServiceLoadsExpressionImagesWithIsolatedTransitions),
        ("Asset service treats missing petting frames as optional", AssetServiceTreatsMissingPettingFramesAsOptional),
        ("Bounded asset cache evicts least recently used entries", BoundedAssetCacheEvictsLeastRecentlyUsedEntries),
        ("Source section extraction handles line endings", SourceSectionExtractionHandlesLineEndings),
        ("Pet window defers optional animation assets", PetWindowDefersOptionalAnimationAssets),
        ("Built-in idle action defines eight authored-rate frame paths", BuiltInIdleActionDefinesEightAuthoredRateFramePaths),
        ("Idle frame diagnostics read all packaged frames", IdleFrameDiagnosticsReadAllPackagedFrames),
        ("Built-in blink action defines random blink frames", BuiltInBlinkActionDefinesRandomBlinkFrames),
        ("Built-in move action defines eight distance-driven paths", BuiltInMoveActionDefinesEightDistanceDrivenPaths),
        ("Move frame paths use app resources", MoveFramePathsUseAppResources),
        ("Move speed constants stay in smooth range", MoveSpeedConstantsStayInSmoothRange),
        ("Expression wheel defines eight items", ExpressionWheelDefinesEightItems),
        ("Expression wheel paths use app resources", ExpressionWheelPathsUseAppResources),
        ("Built-in expression transition actions define shared frames", BuiltInExpressionTransitionActionsDefineSharedFrames),
        ("Expression transition paths use app resources", ExpressionTransitionPathsUseAppResources),
        ("Expression transition planner prefers specific reversible frames", ExpressionTransitionPlannerPrefersSpecificReversibleFrames),
        ("Radial wheel layout keeps generic two-ring geometry", RadialWheelLayoutKeepsGenericTwoRingGeometry),
        ("Radial wheel overlay stays centered on invocation point", RadialWheelOverlayStaysCenteredOnInvocationPoint),
        ("Radial wheel popup overrides WPF edge repositioning", RadialWheelPopupOverridesWpfEdgeRepositioning),
        ("Radial wheel style keeps readable ring hierarchy", RadialWheelStyleKeepsReadableRingHierarchy),
        ("Shortcut wheel loads shell icons", ShortcutWheelLoadsShellIcons),
        ("Pointer gestures classify left click and drag", PointerGesturesClassifyLeftClickAndDrag),
        ("Pointer gestures classify right click movement and hold", PointerGesturesClassifyRightClickMovementAndHold),
        ("Stable pointer gestures keep the traditional context menu", StablePointerGesturesKeepTraditionalContextMenu),
        ("Pointer gestures cancel conflicts and commit once", PointerGesturesCancelConflictsAndCommitOnce),
        ("Interaction coordinator preserves short-click intent", InteractionCoordinatorPreservesShortClickIntent),
        ("Interaction coordinator owns wheel lifecycle", InteractionCoordinatorOwnsWheelLifecycle),
        ("Wheel catalog preserves ordered action references", WheelCatalogPreservesOrderedActionReferences),
        ("Wheel catalog exposes disabled empty shortcut content", WheelCatalogExposesDisabledEmptyShortcutContent),
        ("Wheel catalog service refreshes successful shortcut mutations", WheelCatalogServiceRefreshesSuccessfulShortcutMutations),
        ("Wheel catalog service unsubscribes when disposed", WheelCatalogServiceUnsubscribesWhenDisposed),
        ("Application composes one shared shortcut wheel graph", ApplicationComposesOneSharedShortcutWheelGraph),
        ("Pet window follows live wheel catalog snapshots", PetWindowFollowsLiveWheelCatalogSnapshots),
        ("Radial wheel selector distinguishes all pointer regions", RadialWheelSelectorDistinguishesAllPointerRegions),
        ("Radial wheel second ring stays with category direction", RadialWheelSecondRingStaysWithCategoryDirection),
        ("Radial wheel fast outward motion opens second level", RadialWheelFastOutwardMotionOpensSecondLevel),
        ("Radial wheel controller honors category dwell", RadialWheelControllerHonorsCategoryDwell),
        ("Radial wheel tolerates slight outer overshoot", RadialWheelToleratesSlightOuterOvershoot),
        ("Radial wheel controller resets and collapses state", RadialWheelControllerResetsAndCollapsesState),
        ("Radial wheel controller paginates without persisting controls", RadialWheelControllerPaginatesWithoutPersistingControls),
        ("Shortcut service loads empty state and round trips", ShortcutServiceLoadsEmptyStateAndRoundTrips),
        ("Shortcut service normalizes duplicate identities", ShortcutServiceNormalizesDuplicateIdentities),
        ("Shortcut service appends candidates with contiguous ordering", ShortcutServiceAppendsCandidatesWithContiguousOrdering),
        ("Shortcut service mutates ordered entries", ShortcutServiceMutatesOrderedEntries),
        ("Shortcut service updates program launch options safely", ShortcutServiceUpdatesProgramLaunchOptionsSafely),
        ("Shortcut service enforces its entry limit", ShortcutServiceEnforcesEntryLimit),
        ("Shortcut service recovers malformed storage", ShortcutServiceRecoversMalformedStorage),
        ("Shortcut service isolates malformed entries", ShortcutServiceIsolatesMalformedEntries),
        ("Shortcut service notifies only after persisted mutations", ShortcutServiceNotifiesOnlyAfterPersistedMutations),
        ("Shortcut drop handler classifies existing file system items", ShortcutDropHandlerClassifiesExistingFileSystemItems),
        ("Shortcut drop handler rejects executable scripts", ShortcutDropHandlerRejectsExecutableScripts),
        ("Shortcut drop handler accepts safe web targets", ShortcutDropHandlerAcceptsSafeWebTargets),
        ("Shortcut drop handler accepts Steam game URIs", ShortcutDropHandlerAcceptsSteamGameUris),
        ("Shortcut drop handler rejects missing and unsafe inputs", ShortcutDropHandlerRejectsMissingAndUnsafeInputs),
        ("Shortcut drop handler aggregates mixed batch duplicates", ShortcutDropHandlerAggregatesMixedBatchDuplicates),
        ("Shortcut drop handler reports shortcut limit failures", ShortcutDropHandlerReportsShortcutLimitFailures),
        ("Shortcut launcher creates structured shell start info", ShortcutLauncherCreatesStructuredShellStartInfo),
        ("Shortcut launcher accepts every supported target type", ShortcutLauncherAcceptsEverySupportedTargetType),
        ("Shortcut launcher rejects missing and malformed definitions", ShortcutLauncherRejectsMissingAndMalformedDefinitions),
        ("Shortcut launcher rejects tampered executable file definitions", ShortcutLauncherRejectsTamperedExecutableFileDefinitions),
        ("Shortcut launcher contains and logs start failures", ShortcutLauncherContainsAndLogsStartFailures),
        ("Pet window defines two-level radial overlay and drop surface", PetWindowDefinesTwoLevelRadialOverlayAndDropSurface),
        ("Pet window consumes centralized radial wheel styling", PetWindowConsumesCentralizedRadialWheelStyling),
        ("Pet window routes classified pointer gestures", PetWindowRoutesClassifiedPointerGestures),
        ("Pet window defines hold feedback and petting playback", PetWindowDefinesHoldFeedbackAndPettingPlayback),
        ("Pet window applies per-frame action durations", PetWindowAppliesPerFrameActionDurations),
        ("Pet window schedules directional turns at render priority", PetWindowSchedulesDirectionalTurnsAtRenderPriority),
        ("Pet window completes active movement after one cursor push", PetWindowCompletesActiveMovementAfterOneCursorPush),
        ("Pet window releases runtime resources on close", PetWindowReleasesRuntimeResourcesOnClose),
        ("Pet window detaches context menu subscriptions", PetWindowDetachesContextMenuSubscriptions),
        ("Pet window routes generic radial actions", PetWindowRoutesGenericRadialActions),
        ("Pet window extracts neutral shortcut drop data", PetWindowExtractsNeutralShortcutDropData),
        ("Pet window retires expression-only wheel integration", PetWindowRetiresExpressionOnlyWheelIntegration),
        ("Setting catalog defines every boolean setting once", SettingCatalogDefinesEveryBooleanSettingOnce),
        ("Build feature profiles define stable and preview boundaries", BuildFeatureProfilesDefineStableAndPreviewBoundaries),
        ("Stable setting catalog excludes preview behavior", StableSettingCatalogExcludesPreviewBehavior),
        ("Setting catalog exposes only common direct menu settings", SettingCatalogExposesOnlyCommonDirectMenuSettings),
        ("Setting catalog reads shared settings live", SettingCatalogReadsSharedSettingsLive),
        ("Settings window service reuses the open window", SettingsWindowServiceReusesTheOpenWindow),
        ("Settings window service releases a closed window", SettingsWindowServiceReleasesAClosedWindow),
        ("Settings window defines the approved visual structure", SettingsWindowDefinesTheApprovedVisualStructure),
        ("Settings window supports theme switching and backdrop", SettingsWindowSupportsThemeSwitchingAndBackdrop),
        ("Settings window cancels update work on close", SettingsWindowCancelsUpdateWorkOnClose),
        ("Settings window exposes shortcut launcher management", SettingsWindowExposesShortcutLauncherManagement),
        ("Settings window shares shortcut services and live updates", SettingsWindowSharesShortcutServicesAndLiveUpdates),
        ("Settings shortcut list accepts shared drop data", SettingsShortcutListAcceptsSharedDropData),
        ("Direct menus expose the settings command", DirectMenusExposeTheSettingsCommand),
        ("Input keyboard layout maps common keys", InputKeyboardLayoutMapsCommonKeys),
        ("Input keyboard layout exposes drawable keys", InputKeyboardLayoutExposesDrawableKeys),
        ("Input keyboard layout exposes key labels", InputKeyboardLayoutExposesKeyLabels),
        ("Input reactive state expires highlights", InputReactiveStateExpiresHighlights),
        ("Windows input hook normalizes common keys", WindowsInputHookNormalizesCommonKeys),
        ("Input reactive mode suppresses passive animation", InputReactiveModeSuppressesPassiveAnimation),
        ("Movement planner clamps targets to work area", MovementPlannerClampsTargetsToWorkArea),
        ("Movement planner approaches mouse with cursor offset", MovementPlannerApproachesMouseWithCursorOffset),
        ("Movement planner eases toward target", MovementPlannerEasesTowardTarget),
        ("Movement planner detects close targets", MovementPlannerDetectsCloseTargets),
        ("Movement planner detects mouse approach rest position", MovementPlannerDetectsMouseApproachRestPosition),
        ("Movement controller advances logical positions", MovementControllerAdvancesLogicalPositions),
        ("Movement controller resumes without accumulating visual pause", MovementControllerResumesWithoutAccumulatingVisualPause),
        ("Movement controller schedules bounded wander targets", MovementControllerSchedulesBoundedWanderTargets),
        ("Movement controller advances frames by distance", MovementControllerAdvancesFramesByDistance),
        ("Directional movement turns from front before walking", DirectionalMovementTurnsFromFrontBeforeWalking),
        ("Directional movement does not restart an active turn", DirectionalMovementDoesNotRestartActiveTurn),
        ("Directional movement returns through the same authored frames", DirectionalMovementReturnsThroughSameAuthoredFrames),
        ("Directional movement changes sides through front", DirectionalMovementChangesSidesThroughFront),
        ("Cursor nudge planner nudges nearby cursor", CursorNudgePlannerNudgesNearbyCursor),
        ("Cursor nudge planner ignores distant cursor", CursorNudgePlannerIgnoresDistantCursor),
        ("Cursor nudge planner clamps to work area", CursorNudgePlannerClampsToWorkArea),
        ("Cursor nudge planner detects manual movement cooldown", CursorNudgePlannerDetectsManualMovementCooldown),
        ("Cursor nudge planner blocks while mouse button is pressed", CursorNudgePlannerBlocksWhileMouseButtonIsPressed),
        ("Cursor nudge planner limits continuous push duration", CursorNudgePlannerLimitsContinuousPushDuration),
        ("Cursor push gate blocks repeats until the cursor exits", CursorPushGateBlocksRepeatsUntilCursorExits),
        ("Animation controller loops idle frames", AnimationControllerLoopsIdleFrames),
        ("Pet frame timing resolves authored overrides", PetFrameTimingResolvesAuthoredOverrides),
        ("Animation controller completes one-shot actions", AnimationControllerCompletesOneShotActions),
        ("Animation controller completes expression transitions", AnimationControllerCompletesExpressionTransitions),
        ("Animation controller centralizes passive blockers", AnimationControllerCentralizesPassiveBlockers),
        ("Pet animation timings are responsive", PetAnimationTimingsAreResponsive),
        ("Idle breathing values are neutral during stabilization", IdleBreathingValuesAreNeutralDuringStabilization),
        ("Character stationary animations are enabled", CharacterStationaryAnimationsAreEnabled),
        ("Character assets decode at pet display width", CharacterAssetsDecodeAtPetDisplayWidth),
        ("Asset diagnostics include group and resource path", AssetDiagnosticsIncludeGroupAndResourcePath),
        ("Input reactive asset path uses app resource", InputReactiveAssetPathUsesAppResource),
        ("Input reactive asset is packaged", InputReactiveAssetIsPackaged),
        ("Packaged character assets are display sized", PackagedCharacterAssetsAreDisplaySized),
        ("Packaged expression transitions have complete source and runtime endpoints", PackagedExpressionTransitionsHaveCompleteSourceAndRuntimeEndpoints),
    };
}
